import { Helmet } from 'react-helmet-async';
import { Link } from 'react-router-dom';

const exams = [
  { name: 'UPSC', slug: 'upsc', description: 'Civil Services', color: 'bg-blue-500' },
  { name: 'JEE', slug: 'jee', description: 'Engineering', color: 'bg-green-500' },
  { name: 'SSC CGL', slug: 'ssc-cgl', description: 'Government Jobs', color: 'bg-purple-500' },
  { name: 'Banking', slug: 'banking', description: 'Bank PO/Clerk', color: 'bg-orange-500' },
];

const features = [
  { title: 'AI-Generated Questions', description: 'Exam-level questions generated by AI, reviewed by experts.', icon: 'M9.663 17h4.673M12 3v1m6.364 1.636l-.707.707M21 12h-1M4 12H3m3.343-5.657l-.707-.707m2.828 9.9a5 5 0 117.072 0l-.548.547A3.374 3.374 0 0014 18.469V19a2 2 0 11-4 0v-.531c0-.895-.356-1.754-.988-2.386l-.548-.547z' },
  { title: 'Adaptive Learning', description: 'Questions adapt to your level. Weak areas get more focus.', icon: 'M13 10V3L4 14h7v7l9-11h-7z' },
  { title: 'Mock Tests', description: 'Full-length timed tests with real exam simulation.', icon: 'M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z' },
  { title: 'Performance Analytics', description: 'Track accuracy, speed, and topic mastery over time.', icon: 'M9 19v-6a2 2 0 00-2-2H5a2 2 0 00-2 2v6a2 2 0 002 2h2a2 2 0 002-2zm0 0V9a2 2 0 012-2h2a2 2 0 012 2v10m-6 0a2 2 0 002 2h2a2 2 0 002-2m0 0V5a2 2 0 012-2h2a2 2 0 012 2v14a2 2 0 01-2 2h-2a2 2 0 01-2-2z' },
  { title: 'Mistake Book', description: 'Never repeat mistakes. Auto-track and revise wrong answers.', icon: 'M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253' },
  { title: 'Leaderboard & XP', description: 'Compete with peers. Earn XP, maintain streaks, win badges.', icon: 'M13 7h8m0 0v8m0-8l-8 8-4-4-6 6' },
];

export default function HomePage() {
  return (
    <>
      <Helmet>
        <title>ExamPrep - AI-Powered Competitive Exam Preparation</title>
        <meta name="description" content="Prepare for UPSC, JEE, SSC, Banking, NEET, GATE, CAT exams with AI-generated questions, adaptive learning, mock tests, daily quizzes, and performance analytics. Free to start." />
        <meta name="keywords" content="exam preparation, UPSC preparation, JEE practice, SSC CGL mock test, Banking exam, NEET questions, GATE CS, CAT preparation, AI questions, online test series, India" />
        <meta property="og:title" content="ExamPrep - AI-Powered Competitive Exam Preparation" />
        <meta property="og:description" content="Crack UPSC, JEE, SSC, Banking exams with AI-powered practice. 1500+ questions, daily quizzes, coding challenges. Free to start." />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://examprep.in" />
        <link rel="canonical" href="https://examprep.in" />
        <script type="application/ld+json">{JSON.stringify({
          "@context": "https://schema.org",
          "@type": "FAQPage",
          "mainEntity": [
            {"@type": "Question", "name": "What exams does ExamPrep cover?", "acceptedAnswer": {"@type": "Answer", "text": "ExamPrep covers UPSC, JEE Main & Advanced, SSC CGL, Banking (IBPS/SBI), NEET, GATE CS, CAT, and Coding/IT exams."}},
            {"@type": "Question", "name": "Is ExamPrep free?", "acceptedAnswer": {"@type": "Answer", "text": "Yes! ExamPrep offers a generous free plan with 10 practice sessions/day, daily quizzes, all coding problems, and 30-day analytics. Pro and Premium plans offer additional features."}},
            {"@type": "Question", "name": "How does AI-powered practice work?", "acceptedAnswer": {"@type": "Answer", "text": "Our AI generates exam-level questions adapted to your difficulty level. The system tracks your mastery per topic and adjusts difficulty automatically — harder when you're doing well, easier when you need more practice."}},
            {"@type": "Question", "name": "Can I practice coding questions?", "acceptedAnswer": {"@type": "Answer", "text": "Yes! ExamPrep includes a LeetCode-style coding practice module with an in-browser code editor, test cases, and submission tracking."}}
          ]
        })}</script>
      </Helmet>

      {/* Hero */}
      <section className="relative overflow-hidden bg-gradient-to-br from-primary-50 via-white to-accent-50 dark:from-gray-950 dark:via-gray-900 dark:to-gray-950">
        <div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 sm:py-32 lg:px-8">
          <div className="mx-auto max-w-3xl text-center">
            <h1 className="text-4xl font-extrabold tracking-tight text-gray-900 dark:text-white sm:text-6xl">
              Crack Your Exam with{' '}
              <span className="bg-gradient-to-r from-primary-600 to-accent-600 bg-clip-text text-transparent">
                AI-Powered
              </span>{' '}
              Practice
            </h1>
            <p className="mt-6 text-lg leading-8 text-gray-600 dark:text-gray-400">
              Practice with AI-generated exam-level questions. Adaptive difficulty,
              detailed explanations, and analytics to track your progress. Join 50,000+ aspirants.
            </p>
            <div className="mt-10 flex items-center justify-center gap-4">
              <Link to="/register" className="btn-primary px-8 py-3 text-base">
                Start Practicing Free
              </Link>
              <a href="#features" className="btn-secondary px-6 py-3 text-base">
                See Features
              </a>
            </div>
            <p className="mt-4 text-sm text-gray-500">
              No credit card required. 50 free questions daily.
            </p>
          </div>
        </div>
      </section>

      {/* Exams */}
      <section id="exams" className="bg-white py-20 dark:bg-gray-950">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h2 className="text-3xl font-bold text-gray-900 dark:text-white">
              Choose Your Exam
            </h2>
            <p className="mt-3 text-gray-600 dark:text-gray-400">
              Comprehensive preparation for India's top competitive exams
            </p>
          </div>
          <div className="mt-12 grid gap-6 sm:grid-cols-2 lg:grid-cols-4">
            {exams.map((exam) => (
              <Link
                key={exam.slug}
                to={`/exams/${exam.slug}`}
                className="card group cursor-pointer transition-shadow hover:shadow-md"
              >
                <div className={`mb-4 inline-flex h-12 w-12 items-center justify-center rounded-xl ${exam.color} text-lg font-bold text-white`}>
                  {exam.name.charAt(0)}
                </div>
                <h3 className="text-lg font-semibold text-gray-900 group-hover:text-primary-600 dark:text-white">
                  {exam.name}
                </h3>
                <p className="mt-1 text-sm text-gray-500">{exam.description}</p>
              </Link>
            ))}
          </div>
        </div>
      </section>

      {/* Features */}
      <section id="features" className="bg-gray-50 py-20 dark:bg-gray-900">
        <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
          <div className="text-center">
            <h2 className="text-3xl font-bold text-gray-900 dark:text-white">
              Everything You Need to Succeed
            </h2>
            <p className="mt-3 text-gray-600 dark:text-gray-400">
              Built by aspirants, powered by AI
            </p>
          </div>
          <div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-3">
            {features.map((feature) => (
              <div key={feature.title} className="card">
                <div className="mb-4 inline-flex h-10 w-10 items-center justify-center rounded-lg bg-primary-100 text-primary-600 dark:bg-primary-900/30 dark:text-primary-400">
                  <svg className="h-5 w-5" fill="none" viewBox="0 0 24 24" stroke="currentColor" strokeWidth={2}>
                    <path strokeLinecap="round" strokeLinejoin="round" d={feature.icon} />
                  </svg>
                </div>
                <h3 className="text-base font-semibold text-gray-900 dark:text-white">
                  {feature.title}
                </h3>
                <p className="mt-2 text-sm text-gray-600 dark:text-gray-400">
                  {feature.description}
                </p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="bg-primary-600 py-16">
        <div className="mx-auto max-w-4xl px-4 text-center sm:px-6 lg:px-8">
          <h2 className="text-3xl font-bold text-white">
            Ready to Start Your Preparation?
          </h2>
          <p className="mt-4 text-lg text-primary-100">
            Join thousands of aspirants who are already using ExamPrep to crack their exams.
          </p>
          <Link
            to="/register"
            className="mt-8 inline-flex items-center rounded-lg bg-white px-8 py-3 text-base font-semibold text-primary-600 shadow-sm transition-colors hover:bg-primary-50"
          >
            Get Started Free
          </Link>
        </div>
      </section>
    </>
  );
}
