"""Admin-editable static pages API."""
from fastapi import APIRouter, Depends, Body
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.database import get_db
from app.core.security import require_role
from app.models.user import User
from app.models.page_content import PageContent

router = APIRouter()

# Default content for pages when first created
DEFAULTS = {
    "about": {
        "title": "About ExamPrep",
        "content": """## About ExamPrep

ExamPrep is an AI-powered competitive exam preparation platform built by **ExamPrep Team**.

### Our Mission

We believe every aspirant deserves access to world-class preparation tools, regardless of their location or budget. ExamPrep combines cutting-edge AI with proven pedagogy to level the playing field for competitive exam preparation in India.

### What We Offer

- **AI-Generated Questions** — Exam-level questions generated by AI, adapted to your difficulty level
- **8 Exam Types** — UPSC, JEE, SSC CGL, Banking, NEET, GATE CS, CAT, and Coding
- **Adaptive Learning** — Questions get harder as you improve, easier when you need practice
- **Daily Quizzes** — Fresh 20-question quiz every day with leaderboard
- **Coding Practice** — LeetCode-style problems with in-browser code editor
- **AI Tutor** — Chat with an AI that knows your performance data
- **Study Planner** — Personalized weekly schedule with progress tracking

### Our Team

We are a team of engineers, educators, and exam toppers who understand the challenges aspirants face because we've been through the same journey.

### Contact

Email: support@zencodio.com
""",
    },
    "terms": {
        "title": "Terms and Conditions",
        "content": """## Terms and Conditions

**Last Updated: March 2026**

### 1. Acceptance of Terms

By accessing and using ExamPrep (the "Platform"), you agree to be bound by these Terms and Conditions. If you do not agree, please do not use the Platform.

### 2. User Accounts

- You must be at least 13 years old to create an account.
- You are responsible for maintaining the confidentiality of your account credentials.
- You agree to provide accurate and complete registration information.

### 3. Subscription Plans

- **Free Plan**: Limited features as described on the pricing page.
- **Pro Plan (₹149/month)**: Enhanced features including AI generation and extended analytics.
- **Premium Plan (₹199/month)**: Full access to all features.
- Subscriptions auto-renew unless cancelled before the billing date.

### 4. Content and Intellectual Property

- All questions, explanations, and content on ExamPrep are owned by ExamPrep Team.
- You may not reproduce, distribute, or commercially exploit any content from the Platform.
- User-generated content (notes, discussions) remains your property but you grant us a license to display it.

### 5. AI-Generated Content

- Questions and blog posts may be generated by AI.
- While we strive for accuracy, AI-generated content may contain errors.
- Always cross-verify important information from official sources.

### 6. Refund Policy

- Refund requests must be made within 7 days of purchase.
- Refunds are processed within 5-7 business days.
- No refunds for partial month usage.

### 7. Limitation of Liability

ExamPrep is provided "as is" without warranties. We are not liable for exam results or any decisions made based on our content.

### 8. Changes to Terms

We may update these terms at any time. Continued use of the Platform constitutes acceptance of the updated terms.

### 9. Contact

For questions about these terms, contact us at legal@zencodio.com.
""",
    },
    "privacy": {
        "title": "Privacy Policy",
        "content": """## Privacy Policy

**Last Updated: March 2026**

### 1. Information We Collect

**Personal Information:**
- Name, email address, phone number (during registration)
- Payment information (processed securely via Razorpay)

**Usage Data:**
- Practice session data, quiz scores, test results
- Topic mastery and performance analytics
- Device information and IP address

### 2. How We Use Your Information

- To provide and improve our exam preparation services
- To personalize your learning experience (adaptive difficulty, recommendations)
- To process payments and manage subscriptions
- To send notifications about your practice streak, daily quiz, and achievements
- To generate analytics and performance reports

### 3. Data Sharing

- We do **not** sell your personal data to third parties.
- We may share anonymized, aggregated data for research purposes.
- Payment processing is handled by Razorpay — their privacy policy applies.

### 4. Data Security

- All data is encrypted in transit (HTTPS) and at rest.
- Passwords are hashed using bcrypt.
- JWT tokens are used for authentication with Redis-backed blacklisting.

### 5. Your Rights

- **Access**: You can view all your data through your profile and analytics pages.
- **Delete**: You can delete your account at any time from Profile > Settings > Delete Account.
- **Export**: Contact us to request a data export.

### 6. Cookies

We use cookies for:
- Authentication (JWT tokens)
- Dark mode preference
- Onboarding status

### 7. Children's Privacy

ExamPrep is intended for users aged 13 and above. We do not knowingly collect data from children under 13.

### 8. Changes to This Policy

We will notify users of significant changes to this privacy policy via email or in-app notification.

### 9. Contact

For privacy-related inquiries: privacy@zencodio.com
""",
    },
    "contact": {
        "title": "Contact Us",
        "content": """## Contact Us

We'd love to hear from you! Whether you have a question, feedback, or just want to say hello.

### Email

- **General**: support@zencodio.com
- **Business**: business@zencodio.com
- **Privacy**: privacy@zencodio.com

### Office

ExamPrep Team
Hyderabad, Telangana, India

### Support Hours

Monday - Saturday: 9:00 AM - 6:00 PM IST

### Social Media

Follow us for updates, tips, and daily quiz reminders.
""",
    },
    "disclaimer": {
        "title": "Disclaimer",
        "content": """## Disclaimer

**Last Updated: March 2026**

### General Disclaimer

The information provided on ExamPrep (zencodio.com) is for general educational and informational purposes only. While we strive to keep the information up-to-date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the platform or the information, products, services, or related graphics contained on the platform.

### AI-Generated Content

ExamPrep uses artificial intelligence (Google Gemini AI) to generate practice questions, explanations, blog posts, and study materials. While our AI generates high-quality, exam-level content:

- AI-generated content may occasionally contain inaccuracies or errors.
- The content should not be treated as a substitute for official textbooks, coaching, or exam authority guidelines.
- We recommend users verify critical information from official sources such as UPSC, NTA, SSC, IBPS, and respective exam conducting bodies.

### No Guarantee of Results

ExamPrep is a practice and preparation tool. We do not guarantee:

- Specific exam scores, ranks, or selection outcomes.
- That the questions on our platform will appear in actual exams.
- Accuracy of difficulty level mapping to actual exam standards.

Exam success depends on multiple factors including individual effort, consistency, and overall preparation strategy.

### Third-Party Content

Our platform may contain links to external websites. We do not control and are not responsible for the content, privacy policies, or practices of any third-party websites.

### Changes

We reserve the right to update or modify this disclaimer at any time without prior notice. Users are encouraged to review this page periodically.

### Contact

For questions about this disclaimer, contact us at legal@zencodio.com.
""",
    },
    "dmca": {
        "title": "DMCA Policy",
        "content": """## DMCA Policy

**Last Updated: March 2026**

### Copyright Notice

ExamPrep respects the intellectual property rights of others and expects its users to do the same. In accordance with the Digital Millennium Copyright Act (DMCA), we will respond promptly to claims of copyright infringement committed using our platform.

### Reporting Copyright Infringement

If you believe that content available on ExamPrep infringes your copyright, please send a written notification containing:

1. A physical or electronic signature of the copyright owner or authorized representative.
2. Identification of the copyrighted work claimed to have been infringed.
3. Identification of the material on our platform that is claimed to be infringing, with enough detail for us to locate it.
4. Your contact information (name, address, telephone number, and email).
5. A statement that you have a good faith belief that the use is not authorized by the copyright owner.
6. A statement, under penalty of perjury, that the information in your notice is accurate and that you are the copyright owner or authorized to act on their behalf.

### Send DMCA Notices To

Email: legal@zencodio.com

Subject Line: DMCA Takedown Request

### Counter-Notification

If you believe your content was removed by mistake, you may submit a counter-notification with:

1. Your physical or electronic signature.
2. Identification of the material that was removed and the location where it appeared.
3. A statement under penalty of perjury that you have a good faith belief the material was removed by mistake.
4. Your name, address, and telephone number, and a statement consenting to jurisdiction.

### Repeat Infringers

We may terminate the accounts of users who are repeat infringers.
""",
    },
}


@router.get("/{slug}")
async def get_page(slug: str, db: AsyncSession = Depends(get_db)):
    """Get a static page by slug (public)."""
    result = await db.execute(select(PageContent).where(PageContent.slug == slug, PageContent.is_active == True))
    page = result.scalar_one_or_none()

    if page:
        return {"status": "success", "data": {"title": page.title, "content": page.content, "slug": page.slug}}

    # Return default if not yet saved
    default = DEFAULTS.get(slug)
    if default:
        return {"status": "success", "data": {"title": default["title"], "content": default["content"], "slug": slug}}

    from app.exceptions import NotFoundError
    raise NotFoundError("Page")


@router.put("/{slug}")
async def update_page(
    slug: str,
    body: dict = Body(...),
    db: AsyncSession = Depends(get_db),
    user: User = Depends(require_role("admin")),
):
    """Create or update a static page (admin only)."""
    result = await db.execute(select(PageContent).where(PageContent.slug == slug))
    page = result.scalar_one_or_none()

    if page:
        page.title = body.get("title", page.title)
        page.content = body.get("content", page.content)
    else:
        page = PageContent(slug=slug, title=body["title"], content=body["content"])
        db.add(page)

    await db.commit()
    await db.refresh(page)
    return {"status": "success", "data": {"slug": page.slug, "title": page.title}}
